#!/usr/bin/env bash
set -euo pipefail
root=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
cd "$root"
bash scripts/build_arxiv.sh
bash scripts/build_elsevier.sh
rm -rf .arxiv-package .elsevier-package
mkdir -p .arxiv-package/figures .elsevier-package dist

# arXiv Submission System 1.5 source package: one top-level main.tex,
# a pre-generated compatible BBL, and PDF-only figures.
for required in dist/arxiv.bbl paper/figures/figure_1_concentration_is_not_scaling.pdf paper/figures/figure_2_exact_component_attribution.pdf; do
  test -f "$required" || { echo "Missing required arXiv package input: $required" >&2; exit 1; }
done
sed 's/\\bibliography{references}/\\input{main.bbl}/' paper/arxiv.tex > .arxiv-package/main.tex
cp paper/abstract.tex paper/content.tex paper/references.bib dist/arxiv.bbl .arxiv-package/
mv .arxiv-package/arxiv.bbl .arxiv-package/main.bbl
cp paper/figures/figure_1_concentration_is_not_scaling.pdf .arxiv-package/figures/
cp paper/figures/figure_2_exact_component_attribution.pdf .arxiv-package/figures/
# The package source references PDF figure filenames, not local PNG review files.
sed -i 's/\.png}/.pdf}/g' .arxiv-package/content.tex
( cd .arxiv-package && zip -X -qr "$root/dist/arxiv_source_v1.zip" main.tex abstract.tex content.tex main.bbl references.bib figures )
expected_arxiv_files=$'abstract.tex\ncontent.tex\nfigures/figure_1_concentration_is_not_scaling.pdf\nfigures/figure_2_exact_component_attribution.pdf\nmain.bbl\nmain.tex\nreferences.bib'
actual_arxiv_files=$(zipinfo -1 dist/arxiv_source_v1.zip | LC_ALL=C sort)
test "$actual_arxiv_files" = "$expected_arxiv_files" || {
  echo "arXiv package contains unexpected or missing files:" >&2
  printf '%s\n' "$actual_arxiv_files" >&2
  exit 1
}

# CAS submission source: only assets proven necessary for the active cas-dc wrapper.
test -f dist/elsevier.bbl || { echo "Missing required Elsevier package input: dist/elsevier.bbl" >&2; exit 1; }
mkdir -p .elsevier-package/styles/elsevier .elsevier-package/figures
sed 's/\\bibliography{references}/\\input{elsevier.bbl}/' paper/elsevier.tex > .elsevier-package/manuscript.tex
cat > .elsevier-package/latexmkrc <<'LATEXMKRC'
$ENV{TEXINPUTS} = './styles/elsevier//:./:' . ($ENV{TEXINPUTS} || '');
$ENV{BSTINPUTS} = './styles/elsevier//:./:' . ($ENV{BSTINPUTS} || '');
LATEXMKRC
cp paper/abstract.tex paper/content.tex paper/references.bib dist/elsevier.bbl .elsevier-package/
cp paper/styles/elsevier/cas-dc.cls paper/styles/elsevier/cas-common.sty paper/styles/elsevier/cas-model2-names.bst .elsevier-package/styles/elsevier/
cp paper/figures/figure_1_concentration_is_not_scaling.pdf .elsevier-package/figures/
cp paper/figures/figure_2_exact_component_attribution.pdf .elsevier-package/figures/
( cd .elsevier-package && zip -X -qr "$root/dist/elsevier_submission_source.zip" manuscript.tex abstract.tex content.tex references.bib elsevier.bbl latexmkrc styles figures )
expected_elsevier_files=$'abstract.tex\ncontent.tex\nelsevier.bbl\nfigures/figure_1_concentration_is_not_scaling.pdf\nfigures/figure_2_exact_component_attribution.pdf\nlatexmkrc\nmanuscript.tex\nreferences.bib\nstyles/elsevier/cas-common.sty\nstyles/elsevier/cas-dc.cls\nstyles/elsevier/cas-model2-names.bst'
actual_elsevier_files=$(zipinfo -1 dist/elsevier_submission_source.zip | LC_ALL=C sort)
test "$actual_elsevier_files" = "$expected_elsevier_files" || {
  echo "Elsevier package contains unexpected or missing files:" >&2
  printf '%s\n' "$actual_elsevier_files" >&2
  exit 1
}

validate_arxiv=$(mktemp -d)
validate_elsevier=$(mktemp -d)
trap 'rm -rf "$validate_arxiv" "$validate_elsevier"' EXIT
unzip -q dist/arxiv_source_v1.zip -d "$validate_arxiv"
(
  cd "$validate_arxiv"
  pdflatex -interaction=nonstopmode -halt-on-error -file-line-error main.tex
  pdflatex -interaction=nonstopmode -halt-on-error -file-line-error main.tex
  ! rg -n 'LaTeX Warning: (Reference|Citation) .* undefined|There were undefined references|undefined citations' main.log
)
unzip -q dist/elsevier_submission_source.zip -d "$validate_elsevier"
(
  cd "$validate_elsevier"
  latexmk -pdf -halt-on-error -file-line-error manuscript.tex
  ! rg -n 'LaTeX Warning: (Reference|Citation) .* undefined|There were undefined references|undefined citations' manuscript.log
)
( cd dist && sha256sum manuscript_arxiv_v1.pdf manuscript_elsevier.pdf arxiv_source_v1.zip elsevier_submission_source.zip > SHA256SUMS )
{
  echo '# arXiv package inventory'
  echo
  echo 'Generated by `scripts/package_release.sh` after the clean extracted-package build.'
  echo
  echo '| File | Bytes | SHA-256 | Reason required | Classification |'
  echo '| --- | ---: | --- | --- | --- |'
  while IFS= read -r member; do
    bytes=$(unzip -p dist/arxiv_source_v1.zip "$member" | wc -c | tr -d ' ')
    checksum=$(unzip -p dist/arxiv_source_v1.zip "$member" | sha256sum | awk '{print $1}')
    case "$member" in
      main.tex) reason='top-level arXiv compilation entry point'; class='generated wrapper' ;;
      abstract.tex) reason='shared abstract text'; class='authored source' ;;
      content.tex) reason='shared scientific body'; class='authored source' ;;
      main.bbl) reason='compatible resolved bibliography'; class='generated build output' ;;
      references.bib) reason='bibliography source/provenance'; class='authored source' ;;
      figures/*) reason='PDFLaTeX figure required by content'; class='generated figure' ;;
    esac
    printf '| `%s` | %s | `%s` | %s | %s |\n' "$member" "$bytes" "$checksum" "$reason" "$class"
  done < <(zipinfo -1 dist/arxiv_source_v1.zip | LC_ALL=C sort)
} > paper/metadata/ARXIV_PACKAGE_INVENTORY.md
